# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 639e21e69883a0fc63d5753a818654eb6003df5e216be23b038f0aa53f39c458f0772243efb7fb46f09b249aa31724e26b1725181fc5ba7d640600993f06653d

test:
  secret_key_base: 3bb82f28e7256d50806533a79b17293cc3b6315f689cce543dec716d695b33535e8ce42c34057d54ff8892fa3e9ae8728773a825c037b1c30c81f4262c1f1e81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
